### ISSUE TITLE
What is the proper method of dealing with non standard (3+ letters) currencies?

### ISSUE THREAD

**Issue by fredshevek** [JodaOrg/joda-money#100]
Hi,

I'm trying to use joda-money with cryptocurrencies.

The problem I'm hitting is that there are 4 letters currencies like `USDT`. I tried to include a definition in `/org/joda/money/MoneyDataExtension.csv` but that's being ignored. The documentation on this states the symbol needs to be 3 char long, so I guess it's expected behaviour but I wonder what's the recommended way of dealing with currencies like `USDT`

**Comment by jodastephen** [comment]
As it stands there is no solution for 4 letter currency codes. The library is built around the ISO standard, and that specifies 3 letter codes.
