### ISSUE TITLE
Symbol for INR (₹)

### ISSUE THREAD

**Issue by princebansal** [JodaOrg/joda-money#101]
Hi 
I was using `joda-money` library and observed that it still returns old symbol `Rs.` for currency `INR`. The new symbol was launched in 2010 and is this `₹`. The unicode for this symbol is `U+20B9`. Please update the library to return new symbol. 
Thanks

**Comment by jodastephen** [comment]
The symbol used comes directly from the JDK. As such, it is the JDK data that would need updating:

    public String getSymbol(Locale locale) {
        MoneyUtils.checkNotNull(locale, "Locale must not be null");
        try {
            return Currency.getInstance(code).getSymbol(locale);
        } catch (IllegalArgumentException ex) {
            return code;
        }
    }
