### ISSUE TITLE
Exception when deserializing money with Jackson

### ISSUE THREAD

**Issue by HugoSart** [JodaOrg/joda-money#108]
I'm using BigMoney type for my DTOs, and I'm facing a null pointer exception in the deserialization process with Jackson:
`Method threw 'java.lang.NullPointerException' exception. Cannot evaluate org.joda.money.BigMoney.toString()`

The error seems to happen only when using Feign Client, although I don't think this is related to Feign.

This is the line that throws the error on Jackson side:
```
@Override
public final Object call() throws Exception {
     // 31-Mar-2021, tatu: Note! This is faster than calling without arguments
     //   because JDK in its wisdom would otherwise allocate `new Object[0]` to pass
     return _constructor.newInstance((Object[]) null);
}
```

Seems that Jackson uses the private no args constructor from BigMoney, that is creating a Money with null amount and currency and then face errors when trying to evaluate its methods.
```
private BigMoney() {
        this.currency = null;
        this.amount = null;
}
```

If the Money / BigMoney classes always expect the amount and currency to be non-null, why don't we initialize these values with dummy data instead of null?

**Comment by jodastephen** [comment]
As per the comment in the code, these were added to support JPA. Even if I added dummy non-null data, it wouldn't help Jackson IIUC, because Jackson would not set the actual values during deserialization.

What you need is a Jackson plugin that maps BigMoney to and from a String.
