### ISSUE TITLE
Malformed metadata in maven central repository

### ISSUE THREAD

**Issue by koral--** [JodaOrg/joda-money#116]
POM of version 1.0.2 contains:
`<url>https://www.joda.org/${joda.artifactId}/</url>`
`joda.artifactId` is not evaluated.

![image](https://user-images.githubusercontent.com/3340954/187751837-cf4134f4-4909-4fcb-8af1-897ddddf7dd7.png)
https://search.maven.org/artifact/org.joda/joda-money/1.0.2/jar

**Comment by jodastephen** [comment]
This is really a bug with search.maven.org.

However, I've made changes to remove the parent pom, which I was considering anyway. Doing that should resolve the issue going forward.
