### ISSUE TITLE
Why Money and CurrencyUnit is final ?

### ISSUE THREAD

**Issue by marwin1991** [JodaOrg/joda-money#117]
Why Money and CurrencyUnit is final ?

**Comment by jodastephen** [comment]
They are "value based classes", suitable for conversion to value types when Project Valhalla arrives.
See https://docs.oracle.com/javase/8/docs/api/java/lang/doc-files/ValueBased.html for example.

**Comment by marwin1991** [comment]
Yep, I have figure this out but f.e. BigDecimal made by java is also designe to be value object but is not final.

I have really weird case. 

In my system there is 30 years old "fancy-stupid workaround" and one currency (PLN) instead of code "985" uses "111" and I thougth I can overide Moeny to chnge behavior of get3Code method.

**Comment by jodastephen** [comment]
There is a file [currency](https://github.com/JodaOrg/joda-money/blob/main/src/main/resources/org/joda/money/CurrencyData.csv) that could be replaced to change the code number.

As per the instructions in https://github.com/JodaOrg/joda-money/blob/main/src/main/java/org/joda/money/DefaultCurrencyUnitDataProvider.java you may be able to replace the data without rebuilding the jar file.

**Comment by marwin1991** [comment]
@jodastephen Thank you so much for your help! I think this issue can be closed, and maybe it will help others in the future :)
