### ISSUE TITLE
Croatia goes EUR

### ISSUE THREAD

**Issue by janjaali** [JodaOrg/joda-money#126]
Hi, considering <https://en.wikipedia.org/wiki/Croatia_and_the_euro> - do we need to modify <https://github.com/JodaOrg/joda-money/blob/main/src/main/resources/org/joda/money/CurrencyData.csv> file? Happy to contribute if necessary.

**Comment by jodastephen** [comment]
Yes, this will need a new release. Feel free o raise a PR

**Comment by jodastephen** [comment]
Thanks
