### ISSUE TITLE
Question: French Canadian Dollar Formatting and Symbol Placement

### ISSUE THREAD

**Issue by crgardner** [JodaOrg/joda-money#128]
I probably am overlooking, but does MoneyFormatter support the non-breaking space for French Canadian dollar formatting?

Also, is the MoneyFormatter aware of symbol placement? I know you can build a formatter and specify the amount and currency symbol via the corresponding append commands, but that requires the caller to know in advance what that order should be.

https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_c&page=9Rl-N63dyxbA.html#:~:text=Symbol%20for%20the%20Canadian%20dollar%20in%20French&text=Use%20a%20non%2Dbreaking%20space,25%2C99%20%24%20CA

**Comment by jodastephen** [comment]
The money formatter supports adding a literal, which could be a non-breaking space, something like `appendCurrencyCode().appendLiteral(NON_BREAKING__SPACE).appendAmount()`.

The formatter builder does not have too much localization knowledge, thus it doesn't support symbol placement ATM. I'm not sure what symbol placement would look like in the API, nor do I know a source of data other than CLDR (which is complex), so I'm not planning on adding symbol placement rules myself.
