### ISSUE TITLE
`BigDecimal` `stripTrailingZeros` bug in Android that affects `joda-money` 

### ISSUE THREAD

**Issue by yogurtearl** [JodaOrg/joda-money#129]
`java.math.BigDecimal.valueOf(0.0).stripTrailingZeros()` returns `"0.0"` on Android API 28 and `"0"` on API 30.  

This Android bug impacts `joda-money`: 
https://github.com/JodaOrg/joda-money/blob/63549923396dbe93e0913af71e7ef8a967ded871/src/main/java/org/joda/money/BigMoney.java#L114

On Android API 28: 

`BigMoney.of(EUR, 0.0)` is `"EUR 0.0"` 
and 
`BigMoney.of(EUR, BigDecimal.ZERO)` is `"EUR 0"`

On Android API 30 they both return `"EUR 0"`

This is an bug in old versions of Android... but just filing here for anyone that  may run into this. 

Understandable if `joda-money` doesn't want to try and avoid old Android bugs. 

Related Android bug: 
https://issuetracker.google.com/issues/301570464

**Comment by jodastephen** [comment]
Thanks for documenting this. Joda-Money is compatible with JDK 8 upwards which has the bug fixed. Effectively this means Joda-Money is compatible with Android API 30+. Fortunately, the fix here is simple and only needed in one place, so it is worth doing.
