### ISSUE TITLE
JPA persistence and joda-money

### ISSUE THREAD

**Issue by gabrielbauman** [JodaOrg/joda-money#23]
I have now used Joda Money under a couple of persistence providers (Hibernate and EclipseLink). There are varying levels of support for using Money and BigMoney values as entity fields.

Under Hibernate, there are readily available UserType adapters for Joda Money. Under EclipseLink it's workable but labor intensive - there's no equivalent to Hibernate's UserType stuff, and custom adapters must be written for every entity class that has a Money field.

Why are all these adapters necessary? Simply put, because immutable value types like Money and BigMoney cannot be properly embedded in JPA entities.

In order to be easily embedded, objects must:

- have a default constructor (can be protected)
- support being initialized by reflection
- be marked @javax.persistence.Embeddable

They should also preferably not be marked final, since that keeps the JPA implementation from caching and pooling objects efficiently.

Since Joda Money is undoubtedly being used in many JPA-based applications, it may be worthwhile to ship a mutable BigMoneyProvider implementation that is amenable to being used as @Embeddable.

This would mean that applications could implement the JPA spec and not need to worry about third-party libraries to support Joda Money. It would certainly reduce the work involved in swapping out JPA providers.

Would you accept such an implementation? It would add a compile-time (not runtime) dependency on javax.persistence.Embeddable.

**Comment by jodastephen** [comment]
I assume this was fixed by #61
