### ISSUE TITLE
Restrict currency codes to three letters

### ISSUE THREAD

**Issue by jodastephen** [JodaOrg/joda-money#36]
Parsing assumes three letters but no validation checked it. Allow only upper case letters to avoid clashes between same code in upper and lower case. Extension of #31.

**Comment by techyourchance** [comment]
Hi,
Sorry for necromancing.

I just started used joda-money, and it is great, but one issue bothers me - it does not allow a use of lower case currency codes. I searched through the code and issues and landed here.

I looked through ISO 4217 standard, and haven't found any explicit mention of the case sensitivity of the codes. I'm leaning towards interpreting this as that currency codes are case insensitive per the standard.

Your description above states that the reason for upper case requirement is: 

> to avoid clashes between same code in upper and lower case

Could you elaborate a bit? Is supporting lower case currency codes would be acceptable in your opinion?

If that would be acceptable, I will gladly submit a PR
