### ISSUE TITLE
Some kind of spaces are not parsed correctly

### ISSUE THREAD

**Issue by danielemaddaluno** [JodaOrg/joda-money#53]
Some kind of space character gives me problem, trying the following code:

`Money money = Money.parse("USD 1794.19");`
Gives me a:

`Exception in thread "main" java.lang.IllegalArgumentException: Money amount 'USD 1794.19' cannot be parsed
	at org.joda.money.BigMoney.parse(BigMoney.java:381)
	at org.joda.money.Money.parse(Money.java:339)
	at controllers.Test.main(Test.java:18)`

While replacing that character with a standard space from my keyboard works fine, in fact, 
`Money money = Money.parse("USD 1794.19".replace(" "," "));` executes correctly.

Probably the error above doesn't appear if you just copy paste the code (github parses the string)...
If you want to create a space that gives that error you can go to http://www.unit-conversion.info/texttools/ascii/
select "ASCII Numbers to Text", write in the box above `194 160` and use the char generated in the box below as space in the string `USD 1794.19`.

**Comment by jodastephen** [comment]
The `parse()` method is intended to parse just an ASCII space. It is not intended to be a lenient parser, but a strict one, that handles machine to machine communication.
