### ISSUE TITLE
Does not work well with spring data mongodb

### ISSUE THREAD

**Issue by ashish12** [JodaOrg/joda-money#54]
Using spring data mongodb to store/retrieve Money object does not work well, as it depends on the constructor argument names to match the field names of the stored document.
So basically if we save Money.of("USD", 30), it gets saved in mongodb as { amount: 30, currency: {code: ..., numericCode:..., decimalPlaces:...}}, but the constructor arguments are code, numericCurrencyCode and decimalPlaces.
While trying to deserialize the json, there is an exception as numericCurrencyCode is not available in the stored document. There is a workaround available by defining a custom converter, but seems to be unnecessary work if the field and constructor argument name can be consistent in CurrencyUnit, unless there is an overriding reason for them to be different. If this seems like a reasonable proposal, I am willing to submit a pull request.

**Comment by jodastephen** [comment]
Fix applied, thanks

**Comment by ashish12** [comment]
Thanks.

May I know when this would be released?

**Comment by jodastephen** [comment]
There are no firm release plans at this point. I generally wait until there are a few things to release.
