### ISSUE TITLE
Why to throw exceptions on converting same currencies

### ISSUE THREAD

**Issue by chuwy** [JodaOrg/joda-money#63]
Sorry if it's wrong place to ask.
But I'm wondering about reasons to make this library decision: https://github.com/JodaOrg/joda-money/blob/master/src/main/java/org/joda/money/BigMoney.java#L1539-L1540
Why not just multiply by 1?

**Comment by jodastephen** [comment]
What if someone requests conversion from USD to USD with rate 1.1? Should the system reject that? ie. just because the currencies are the same, it is not enough to say that the result is "no change".

**Comment by chuwy** [comment]
Hm. Probably that makes sense. I asked because in our use case, app receives rates from Open Exchange Rates and if I understand it correct, this rate anyway should be correct (1.0). Thus I was not taking rate in account. However, this was still very unexpected.
