### ISSUE TITLE
Indian currency formatting 

### ISSUE THREAD

**Issue by vikrim1** [JodaOrg/joda-money#74]
Hi @jodastephen , thank you for your work here!

This is regarding the commit e8c83944f5d6407007d41de2fa89d79ab68f18af

I'm trying to achieve proper formatting for number groups for Indian Rupees (eg. 1,00,000). I was hoping that this commit would do that for me, but it looks like
MoneyAmountStyle.getLocalizedStyle(Locale locale)
still always returns 0 as the extendedGroupingSize.

Will there be some update in DecimalFormat that will eventually pass in the right extendedGroupingSize for let's say a locale of hi_IN, and this will be passed to MoneyAmountStyle?

Or am I missing how to use this to properly format Indian numbers? Right now it feels like I can't really achieve this without constructing my own MoneyAmountStyle, which I also can't do because of its private constructor / setters.

Thanks!

**Comment by jodastephen** [comment]
You should be able to use `withExtendedGroupingSize()` on `MoneyAmountStyle` to get the setting you want.

**Comment by vikrim1** [comment]
Doh. Missed those with() methods. Works great, thanks!

I’m assuming you’re not planning on changing the NumberFormat library to the ICU (http://site.icu-project.org/ <http://site.icu-project.org/>) version to support this formatting in the auto-localized version?

**Comment by jodastephen** [comment]
ICU is a large library and would not be suitable as a dependency. If something needs fixing or changing here, let me know.
