### ISSUE TITLE
Add support for former currencies

### ISSUE THREAD

**Issue by deniss-s** [JodaOrg/joda-money#75]
Some currencies are not in use any more, e.g. LVL (https://en.wikipedia.org/wiki/Latvian_lats), LTL (https://en.wikipedia.org/wiki/Lithuanian_litas), however currency rates for passed years contain these currencies, which causes IllegalCurrencyException.
Can you come up with additional ConcurrentMap for unused, but still legal currencies?

**Comment by deniss-s** [comment]
I've found out that these are used historical currency codes 
https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes

**Comment by jodastephen** [comment]
Proper support for current vs historical would be a good addition. I don't have much time to work on Joda-Money however. Anyone looking to help and raise a PR should comment here!

**Comment by wolftobias** [comment]
I`ve the same issue, LVL ist not being found by joda money and I try to get the exchange rates from "codebase.com" which is a modern crypto currency stock market.

**Comment by jodastephen** [comment]
I'm adding old EUR currencies. PRs can be raised for any others that matter (ie. were reasonably widely used, not just ancient ones for the sake of it)

**Comment by Rameez102** [comment]
Is there anyone solve this problem? If yes, Can you please send me repository where I can download or check the code.

**Comment by wolftobias** [comment]
Unfortunately not, with me was the problem that the brokers is sending in his courses outdated currencies. You have to create a CSV file with the values yourself.

**Comment by jodastephen** [comment]
PRs for old currencies can now be accepted (for previously valid ISO currency codes). See [here](https://github.com/JodaOrg/joda-money/blob/master/src/main/resources/org/joda/money/CurrencyData.csv) for the format.
