### ISSUE TITLE
Print with currency symbol instead of code

### ISSUE THREAD

**Issue by ArtworkAD** [JodaOrg/joda-money#76]
Hey,

```
val money = Money.parse("EUR 4.5")
textView.setText(money.toString())
```

will show `EUR 4.50`. Is it possible to get `4.50 €` instead?

**Comment by jodastephen** [comment]
You can use a formatter. See the [tests](appendCurrencySymbolLocalized). Something like this:

    MoneyFormatter f = new MoneyFormatterBuilder().appendCurrencySymbolLocalized().toFormatter();
    String s = f.print(money);
