### ISSUE TITLE
add support for more currencies 

### ISSUE THREAD

**Issue by wolftobias** [JodaOrg/joda-money#83]

**Comment by wolftobias** [comment]
I need the following additional currencies, there some crypto currencies, former and existing currencies missing.

#Code,Numeric,DecPlaces,CountryCodes
BTC,-1,8,#Bitcoin
BCH,-1,8,#Bitcoin Cash
BYR,974,0,BY
CLF,990,4,#Special
CUC,931,2,#Special
EEK,-1,2,EE
ETH,-1,9,#Ethereum
GGP,-1,2,GG
IMP,-1,2,#Isle of Man Pound
JEP,-1,2,#Jersey Pound
LTC,-1,8,#LiteCoin
LVL,-1,2,LT
LTL,-1,2,
MTL,-1,2,#Maltese Liras
ZMK,-1,2,#Kwachas - Zambia

**Comment by jodastephen** [comment]
You can add these by creating a file on the classpath: `/org/joda/money/MoneyDataExtension.csv`

**Comment by wolftobias** [comment]
I know, but why do you not extend the API? That was the reason for the Ticket.
