### ISSUE TITLE
joda-money vs JSR 354 RI

### ISSUE THREAD

**Issue by thomashaselwanter** [JodaOrg/joda-money#84]
Hi,

This is not an issue, please feel free to label it as a discussion. There are currently two major implementations for handling money in Java. joda-money and the JSR 354 reference implementation a.k.a moneta. I come here looking for some insights as the author of joda-money was also involved the in JSR 354.

From what I can see joda-money is a high quality library which served as de facto standard for money before (and possibly even beyond) JSR 354. JSR 354 was at some point supposed to be in JDK 9 but never made it there. There seem to have been quite a few disagreements within JSR 354 during it's development.
I noticed that for joda-time the author itself recommends switching to JSR 310, which was included in the JDK, but for joda-money I find no such recommendation to switch to JSR 354.

Normally I would have naturally gravitated towards an agreed standard when choosing a library for a new project, but the fact that JSR 354 was not accepted into the JDK and that a respected open source author who was part of the JSR does not recommend switching makes me think twice. Development of the JSR 354 RI also seems to have (almost) grinded to a halt, while joda-money is a little more active. Adoption of JSR 354 also seems limited as this point. It is easier to find projects that integrate with or extend joda-money than it is to find such projects for JSR 354.

So jodastephen, can you tell me what went wrong with JSR 354?

If anybody else has some insight about pros/cons of each implementation and if one is more suited to a particular type of application than the other, let's hear it.

Thanks!

**Comment by jodastephen** [comment]
Although I was part of the expert group of JSR-354, I was not really that active.

The key problem that money faces is that `BigDecimal` is *****. Trying to build a `Money` class whilst that remains true is tricky and prone to difficulty. As such, the JDK did, and will likely continue to, reject any addition of a `Money` class until a replacement for `BigDecimal` exists. This will occur when Java includes value types, something likely to be 5 years away or so.

In the meantime, Joda-Money continues as a long term stable API for money, although I don't have that much time to tackle issues, or extend the formatting.

**Comment by thomashaselwanter** [comment]
So what you are essentially saying is that by the time a `Money` class makes it into the JDK years down the road it won't look anything like what we currently have in JSR-354, because it will be based on new value types. Therefore there is little to no benefit attached to the standardization that JSR-354 provides. It is a helpful piece of information that the rejection to include JSR-354 into the JDK was based on shortcomings of `BigDecimal` and the future introduction of value types. Thanks!
