### ISSUE TITLE
Initialize an empty provider of currencies?

### ISSUE THREAD

**Issue by wasowski** [JodaOrg/joda-money#86]
Is it possible to start with no currencies defined? I would like to be able to define (register) all my currencies at runtime, not relying on static files, but could not figure out how to do this.

(alternatively, I could also live with being able to redefine currencies, for instance to change scale, but I suppose this is hard to do, given that there might be values in a given currency living around at existing scale).

**Comment by wasowski** [comment]
Sorry. I just realized that I can use the forced mode of ``CurrencyUnit.registerCurrency`` . This will certainly do for my case.  I can close this issue - I will keep it open to let you respond, whether it is possible to start with an empty database and avoid using the forced mode.

**Comment by jodastephen** [comment]
The best option here is probably to set the `org.joda.money.CurrencyUnitDataProvider` Java property on the command line to a class of your own, allowing you to register your own data in a convenient central location.
