### ISSUE TITLE
Addition operations in money

### ISSUE THREAD

**Issue by ghacupha** [JodaOrg/joda-money#87]
A question: to what extent is the Money class immutable, or why is this test failing ?

```
@Test
    public void jodaMoneyTest() throws Exception {
        Money amount = Money.of(CurrencyUnit.getInstance("USD"),12);
        Money fiveDollars = Money.of(CurrencyUnit.getInstance("USD"),5);

        amount.plus(fiveDollars);

        System.out.println(amount);

        assertEquals(amount,Money.of(CurrencyUnit.getInstance("USD"),17));
    }
```

**Comment by jodastephen** [comment]
Joda-Money classes are fully immutable. You need to write `amount = amount.plus(fiveDollars);` to get the test to pass. The original instance is not updated.

**Comment by ghacupha** [comment]
Awesome. I'd not thought of doing a reassignment. Thanks
