### ISSUE TITLE
Joda-Money 1.0 not available on maven central

### ISSUE THREAD

**Issue by boomesh** [JodaOrg/joda-money#91]
I'm looking here: http://repo1.maven.org/maven2/org/joda/joda-money/

and the latest I see is `0.9.1`.  The documentation mentions that 1.0 is the latest stable.  Is there a mismatch here?

**Comment by jodastephen** [comment]
The website is currently wrong. v0.9.1 is the latest right now.

**Comment by johanhammar** [comment]
The README.md is also referencing the 1.0 release. I've seen that there has been a few commits last month, is there a planned 1.0 release soon?

**Comment by jodastephen** [comment]
Thats the plan, sorry for the confusion

**Comment by jodastephen** [comment]
I've released v0.90. If someone can confirm it works for them, I can move onto release v1.0. (v0.90 differs in that the currency data files have been majorly refactored, which won't affect you unless you have your own currency data).

Note that v1.0 will be Java 8 only and contain a `module-info.class`.

**Comment by johanhammar** [comment]
I verified v.090 in one of our applications by running the test suite and doing some regression testing.  Seems to work for us.

By the way, thanks for the quick reply!

**Comment by jodastephen** [comment]
v1.0 is released
