### ISSUE TITLE
Add .isGreaterThanOrEqual() and isLessThanOrEqual()

### ISSUE THREAD

**Issue by stickfigure** [JodaOrg/joda-money#98]
Enhancement request: There's currently `isGreaterThan()` and `isEqual()` but no `isGreaterThanOrEqual()`. Same with LessThan. Those methods would be super convenient!

**Comment by jodastephen** [comment]
The same request could be made of Joda-Time and JSR-310. I've always avoided adding those two extra methods, as they ultimately feel like one convenience too many.

**Comment by stickfigure** [comment]
At least with `Instant`, I don't think it's very common to consider millisecond-precision (or nanosecond-precision) comparisons. Unless you're working in physics, one is generally either bigger or less than the other.

On the other hand, Money is frequently compared for penny-exactness. You can withdraw amounts less than or equal to your balance; you can buy something if your wallet contains the price or more. I find myself calling `money.compareTo(otherMoney) >=` et all frequently.

**Comment by jodastephen** [comment]
I'll leave the RFE open and see if it gets any support.
