### ISSUE TITLE
Javadoc on latest release

### ISSUE THREAD

**Issue by ryguy40** [JodaOrg/joda-money#99]
When placing the jodamoney library in Netbeans, I get this error when pointing to the javadoc.jar: https://www.dropbox.com/s/z18xyp0h26ueadh/jodamoney%20javadoc.PNG?dl=0.

Thanks for this great library.

**Comment by jodastephen** [comment]
Your link is private. I suspect the problem is that the Javadoc is built using Java 9 or later and is modular, and that your tooling can't cope. If so, you'll need to complain to your tooling provider.

**Comment by ryguy40** [comment]
Re: private dropbox: Oops. I always forget my organization doesn't allow me to send dropbox links.

Re: Java 9. Yes I'm using Netbeans 8.2 which is not compatible with Java 9. It's really neither here nor there for me personally because the sources.jar is sufficient for Netbeans to give you complete Javadoc functionality. I just thought you'd like to know. (then again, maybe I should stop being a curmudgeon and embrace Java 9+... but we hates it...)

The Netbeans error message is:

> <html><strong><p>Invalid Javadoc root Z:\Dropbox\Dropbox (UFL)\Documents\java libraries\joda-money-1.0.1\joda-money-1.0.1-javadoc.jar</p></strong><p>The Javadoc root does not contain the package-list file.</p>

Thanks again for the great work you do.

**Comment by jodastephen** [comment]
There seem to be [various](https://issues.apache.org/jira/browse/MJAVADOC-561) [issues](https://bugs.openjdk.java.net/browse/JDK-8191363) around this. Its not up to this project to fix, as our jar file is perfectly normal/correct AFAICT.

**Comment by jodastephen** [comment]
The file `package-list` was added a while back.
